package client;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class ChatClient extends  ChatClient_AutoGenerated {

    public ChatClient()
    {   
        //TODO Additional initialization
    }
    
    public ChatClient(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
    @Override
    protected IChatEv get_inIncomingEndpointImplementation()
    {
         //TODO return  end-point implementation for IChatEv as following:
         //return new <implementation of inIncomingEndpointImplementation implementing type IChatEv>();
         //Please note that : Uninitialized inIncomingEndpointImplementation results in a RuntimeException
         return null;
    }
    
   
}
