package Test;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class A extends  A_AutoGenerated {

    public A()
    {   
        //TODO Additional initialization
    }
    
    public A(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
    @Override
    protected IIncoming get_inIncomingEndpointImplementation()
    {
         //TODO return  end-point implementation for IIncoming as following:
         //return new <implementation of inIncomingEndpointImplementation implementing type IIncoming>();
         //Please note that : Uninitialized inIncomingEndpointImplementation results in a RuntimeException
         return null;
    }
    
   
}
