package Test;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class B extends  B_AutoGenerated {

    public B()
    {   
        //TODO Additional initialization
    }
    
    public B(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
   
}
