package server;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class ChatServer extends  ChatServer_AutoGenerated {

    public ChatServer()
    {   
        //TODO Additional initialization
    }
    
    public ChatServer(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
    @Override
    protected IChat get_chatIncomingEndpointImplementation()
    {
         //TODO return  end-point implementation for IChat as following:
         //return new <implementation of chatIncomingEndpointImplementation implementing type IChat>();
         //Please note that : Uninitialized chatIncomingEndpointImplementation results in a RuntimeException
         return null;
    }
    
   
}
