package Server;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class MessageParser extends  MessageParser_AutoGenerated {

    public MessageParser()
    {   
        //TODO Additional initialization
    }
    
    public MessageParser(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
    @Override
    protected Server.IMessageParser get_messengerInIncomingEndpointImplementation()
    {
         //TODO return  end-point implementation for Server.IMessageParser as following:
         //return new <implementation of messengerInIncomingEndpointImplementation implementing type Server.IMessageParser>();
         //Please note that : Uninitialized messengerInIncomingEndpointImplementation results in a RuntimeException
         return null;
    }
    
   
}
