package Server;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class MessageReceiver extends  MessageReceiver_AutoGenerated {

    public MessageReceiver()
    {   
        //TODO Additional initialization
    }
    
    public MessageReceiver(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
    @Override
    protected Server.IMessageChannel get_messageInIncomingEndpointImplementation()
    {
         //TODO return  end-point implementation for Server.IMessageChannel as following:
         //return new <implementation of messageInIncomingEndpointImplementation implementing type Server.IMessageChannel>();
         //Please note that : Uninitialized messageInIncomingEndpointImplementation results in a RuntimeException
         return null;
    }
    
   
}
