package Server;
      
import edu.uci.isr.myx.fw.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

public abstract class MessageParser_AutoGenerated extends  AbstractMyxSimpleBrick{ 
    //generated end-point MYX NAME
    public static final IMyxName INTERFACE_NAME_INCOMING_messengerIn =  MyxUtils.createName("messengerIn");
    
    //generated end-point instances
    protected Server.IMessageParser messengerInIncomingEndpointImplementation;
    
         
    public MessageParser_AutoGenerated(){
        //(Auto-generated):  Default constructor
        
        
        this.messengerInIncomingEndpointImplementation = get_messengerInIncomingEndpointImplementation();
        verifyIsNotNull("messengerInIncomingEndpointImplementation" , messengerInIncomingEndpointImplementation); 
        
    }
    
    public MessageParser_AutoGenerated(Properties props){
        //TODO (Auto-generated):   constructor
    }
    
    @SuppressWarnings("unchecked")
    private <T>  void configureOutgoingEndpoint(IMyxName myxName, ArrayList<T> endpointImpls)
    {
        Object [] objs = MyxUtils.getRequiredServiceObjects(this, myxName);
        if ( objs != null)
        {   
            for ( Object obj : objs)
            {
                endpointImpls.add((T)obj);
            }
        }
    }
    //incoming end-points setup methods
    
    /**
     * Gets and initialises messengerInIncomingEndpointImplementation endpoint's concrete implementation   
     * so that it can be returned by the getServiceObject.
     * By default messengerInIncomingEndpointImplementation , which cause RuntimeException
     * if not properly initialized. 
     */
     protected abstract Server.IMessageParser get_messengerInIncomingEndpointImplementation();
    
    
    protected <T> void verifyIsNotNull(String interaceNameString, T interfaceImplementation)
    {
        if  ( interfaceImplementation  == null)
            throw new RuntimeException (interaceNameString + " is Null. Please assign your implementation by overriding configureIncomingEndpoint method." ); 
    }
     
    @Override
    public void begin(){
        //TODO (Auto-generated):  Add initialization codes
        
        
    }
    @Override
    public void end(){
        //(Auto-generated): Add cleanup codes
        //(Auto-generated): Dispose unmanaged resources
    }
    
    @Override
    public Object getServiceObject(IMyxName name) {
        //(Auto-generated): Add your code here
        
        if(name.equals(INTERFACE_NAME_INCOMING_messengerIn)){
          if(messengerInIncomingEndpointImplementation == null){
              throw new RuntimeException("messengerInIncomingEndpointImplementation is Null . Please initialize messengerIn_Impl with Service(/ServiceProxy) .");
          }
          return messengerInIncomingEndpointImplementation;
        } 
        
        return null;
    }
}
