package Server;
      
import edu.uci.isr.myx.fw.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

public abstract class MessageReceiver_AutoGenerated extends  AbstractMyxSimpleBrick{ 
    //generated end-point MYX NAME
    public static final IMyxName INTERFACE_NAME_OUTGOING_messengerOut =  MyxUtils.createName("messengerOut");
    public static final IMyxName INTERFACE_NAME_INCOMING_messageIn =  MyxUtils.createName("messageIn");
    
    //generated end-point instances
    protected ArrayList<Server.IMessageParser> messengerOutOutgoingEndpointImplementations;
    protected Server.IMessageChannel messageInIncomingEndpointImplementation;
    
         
    public MessageReceiver_AutoGenerated(){
        //(Auto-generated):  Default constructor
        this.messengerOutOutgoingEndpointImplementations = new ArrayList<Server.IMessageParser>(); 
        
        
        this.messageInIncomingEndpointImplementation = get_messageInIncomingEndpointImplementation();
        verifyIsNotNull("messageInIncomingEndpointImplementation" , messageInIncomingEndpointImplementation); 
        
    }
    
    public MessageReceiver_AutoGenerated(Properties props){
        //TODO (Auto-generated):   constructor
    }
    
    @SuppressWarnings("unchecked")
    private <T>  void configureOutgoingEndpoint(IMyxName myxName, ArrayList<T> endpointImpls)
    {
        Object [] objs = MyxUtils.getRequiredServiceObjects(this, myxName);
        if ( objs != null)
        {   
            for ( Object obj : objs)
            {
                endpointImpls.add((T)obj);
            }
        }
    }
    //incoming end-points setup methods
    
    /**
     * Gets and initialises messageInIncomingEndpointImplementation endpoint's concrete implementation   
     * so that it can be returned by the getServiceObject.
     * By default messageInIncomingEndpointImplementation , which cause RuntimeException
     * if not properly initialized. 
     */
     protected abstract Server.IMessageChannel get_messageInIncomingEndpointImplementation();
    
    
    protected <T> void verifyIsNotNull(String interaceNameString, T interfaceImplementation)
    {
        if  ( interfaceImplementation  == null)
            throw new RuntimeException (interaceNameString + " is Null. Please assign your implementation by overriding configureIncomingEndpoint method." ); 
    }
     
    @Override
    public void begin(){
        //TODO (Auto-generated):  Add initialization codes
        configureOutgoingEndpoint(INTERFACE_NAME_OUTGOING_messengerOut, this.messengerOutOutgoingEndpointImplementations);  
        
        
    }
    @Override
    public void end(){
        //(Auto-generated): Add cleanup codes
        //(Auto-generated): Dispose unmanaged resources
    }
    
    @Override
    public Object getServiceObject(IMyxName name) {
        //(Auto-generated): Add your code here
        
        if(name.equals(INTERFACE_NAME_INCOMING_messageIn)){
          if(messageInIncomingEndpointImplementation == null){
              throw new RuntimeException("messageInIncomingEndpointImplementation is Null . Please initialize messageIn_Impl with Service(/ServiceProxy) .");
          }
          return messageInIncomingEndpointImplementation;
        } 
        
        return null;
    }
}
