package Chat;       

import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public  class Client extends  Client_AutoGenerated {

    public Client()
    {   
        //TODO Additional initialization
    }
    
    public Client(Properties props)
    {
        super ( props);
        //TODO Additional initialization
    }
    
    @Override
    public void begin()
    {
        super.begin();
        
        //TODO : Additional logic
    }
    
    @Override
    public void end()
    {
        super.end();
        
        //TODO : Additional logic
    }
    
    
   
}
